#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
#  photo_sort.py
#
#  Copyright (c) 2019 Dominic Davis-Foster <dominic@davis-foster.co.uk>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#

#
# generated by wxGlade 0.9.3 on Sun Jul 14 21:24:46 2019
#

import wx
from photo_sort.Launcher import Launcher


class photo_sort(wx.App):
	def OnInit(self):
		self.photo_sort = Launcher(None, wx.ID_ANY, "")
		self.SetTopWindow(self.photo_sort)
		self.photo_sort.Show()
		return True

# end of class photo_sort

if __name__ == "__main__":
	photo_sort = photo_sort(0)
	photo_sort.MainLoop()
